---
# initial setup for ansible to run.
# add public key and set nopassword sudo
- name: ssh key
  authorized_key: user=cloud key="{{ lookup('file','id_rsa.pub') }}"
- name: sudoers
  lineinfile: "dest=/etc/sudoers state=present line='cloud ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'"

